### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by padhu1980** [GrayGalaxy/jiosaavn-downloader#13]
### What happened?

Getting this error.
Uncaught (in promise) TypeError: Failed to fetch
in src/downloader.js:25 
please solve this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by GrayGalaxy** [comment]
I am working on the extension from the ground up. The previous version has some bugs. I will soon upload the new version when it is released.

**Comment by GrayGalaxy** [comment]
@padhu1980 you can now download songs in m4a format with the latest release, checkout [here](https://github.com/GrayGalaxy/jiosaavn-downloader/releases), grant it, the downloaded songs do not have their meta tags. and you will need another extension to be able to download.

For now it still have some bugs and problems. I ma working on the fixes and building a completely standalone extension. It is mostly done. Stay tuned.
