### ISSUE TITLE
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536. Could not load manifest.

### ISSUE THREAD

**Issue by digantasm** [GrayGalaxy/jiosaavn-downloader#20]
### Preflight Checklist

- [X] Checkout the [Known Issues](https://github.com/GrayGalaxy/jiosaavn-downloader/releases) posted on release notes.
- [X] I agree to follow the [Code of Conduct](https://github.com/GrayGalaxy/graygalaxy/blob/main/code_of_conduct.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### What happened?

Tell us what you observed...
Unable to install

- URL: chrome://extensions/
- Browser: Chrome
Error While Installing
![Untitled](https://user-images.githubusercontent.com/81884781/155726239-cc7a51bb-fdb7-48ce-95a2-b726d90e2f84.png)

Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.
Could not load manifest.

**Comment by GrayGalaxy** [comment]
This issue is fixed in release [v22.2.26](https://github.com/GrayGalaxy/jiosaavn-downloader/releases/tag/v22.2.26)
