### ISSUE TITLE
Quality selector does not load on small screens

### ISSUE THREAD

**Issue by GrayGalaxy** [GrayGalaxy/jiosaavn-downloader#3]
On small screen the quality selector dropdown does not loads.\
This is mainly because there is no header in small screen. Even if I manage to somehow add the button the UI does not match

**Comment by GrayGalaxy** [comment]
@jineshpatel30 the bugs you mentioned are fixed in [v0.7](https://github.com/GrayGalaxy/jiosaavn-downloader/releases/tag/v0.7) release

**Comment by jineshpatel30** [comment]
> @jineshpatel30 the bugs you mentioned are fixed in [v0.7](https://github.com/GrayGalaxy/jiosaavn-downloader/releases/tag/v0.7) release

Great, thanks for fixing them quickly :)
